// ══════════════════════════════════════════════════════════════
// API client — secure fetch wrapper around the Hono backend.
//
// Mirrors ../roomalyzer20/src/services/apiClient.js:
//   - Firebase JWT → Authorization: Bearer <token>
//   - Active tenant → X-Tenant-Id header (backend validates membership)
//   - X-Request-Id for traceability
//   - On 401, force Firebase token refresh and retry ONCE
//
// Types are sourced from `./schema` which is generated by
// `npm run gen:api` from the server's OpenAPI spec.
// ══════════════════════════════════════════════════════════════
import { env } from '@/lib/env';
import { storage, StorageKeys } from '@/lib/storage';
import { generateRequestId } from '@/lib/requestId';
import { getIdToken, isFirebaseConfigured } from '@/services/auth/firebase';

export class ApiError extends Error {
  status: number;
  data: unknown;
  constructor(message: string, status: number, data: unknown) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.data = data;
  }
}

async function buildHeaders(forceRefresh: boolean): Promise<Record<string, string>> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    Accept: 'application/json',
    'X-Request-Id': generateRequestId(),
  };

  const tenantId = storage.getString(StorageKeys.ACTIVE_TENANT);
  if (tenantId) headers['X-Tenant-Id'] = tenantId;

  if (isFirebaseConfigured()) {
    const token = await getIdToken(forceRefresh);
    if (token) headers['Authorization'] = `Bearer ${token}`;
  }

  return headers;
}

async function parseResponse(res: Response): Promise<unknown> {
  const text = await res.text();
  let data: unknown = {};
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      if (!res.ok) {
        throw new ApiError(`Server error (${res.status})`, res.status, text);
      }
      throw new ApiError('Invalid JSON in response', res.status, text);
    }
  }

  if (!res.ok) {
    const d = data as { error?: string; message?: string; detail?: string };
    const msg = d.detail
      ? `${d.error ?? d.message ?? `HTTP ${res.status}`}: ${d.detail}`
      : (d.error ?? d.message ?? `HTTP ${res.status}`);
    throw new ApiError(msg, res.status, data);
  }
  return data;
}

async function request<T>(method: string, path: string, body?: unknown): Promise<T> {
  const url = `${env.apiBaseUrl}/api${path}`;

  const doFetch = async (force: boolean) => {
    const headers = await buildHeaders(force);
    const opts: RequestInit = { method, headers };
    if (body !== undefined && body !== null) opts.body = JSON.stringify(body);
    return fetch(url, opts);
  };

  let res = await doFetch(false);
  if (res.status === 401 && isFirebaseConfigured()) {
    res = await doFetch(true);
  }
  return parseResponse(res) as Promise<T>;
}

export const apiClient = {
  get: <T>(path: string) => request<T>('GET', path),
  post: <T>(path: string, body?: unknown) => request<T>('POST', path, body),
  put: <T>(path: string, body?: unknown) => request<T>('PUT', path, body),
  patch: <T>(path: string, body?: unknown) => request<T>('PATCH', path, body),
  delete: <T>(path: string, body?: unknown) => request<T>('DELETE', path, body),
};
