export { apiClient, ApiError } from './client';
export {
  api,
  indeklimaApi,
  authApi,
  sensorTypesApi,
  waterApi,
  adminApi,
} from './typed';
export type {
  paths,
  components,
  Sensor,
  SensorGroup,
  HistoryResponse,
  Alert,
  SensorThresholds,
  ScopeThresholds,
  ThresholdScopeType,
  SensorTypeDef,
  IndeklimaLocation,
  SensorPositions,
  WaterDashboardResponse,
  WaterDashboardKpi,
  WaterAlarm,
  WaterAlarmStatus,
  WaterSilentSensor,
  WaterHeartbeat,
  WaterConfig,
  WaterConfigUpdateBody,
  WaterAlarmAckBody,
  WaterAlarmAttachment,
  WaterMapDataItem,
  WaterMapStatus,
  AdminSensor,
} from './typed';
